-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.barang
(
    id_barang character(50) COLLATE pg_catalog."default" NOT NULL,
    nama_barang integer,
    stok character(50) COLLATE pg_catalog."default",
    satuan_id integer,
    jenis_id integer,
    CONSTRAINT "Barang_pkey" PRIMARY KEY (id_barang)
);

CREATE TABLE IF NOT EXISTS public.barang_keluar
(
    barang_id character(50) COLLATE pg_catalog."default",
    id_barang_keluar character(50) COLLATE pg_catalog."default" NOT NULL,
    jumlah_keluar integer,
    tanggal_keluar date,
    user_id integer,
    CONSTRAINT barang_keluar_pkey PRIMARY KEY (id_barang_keluar)
);

CREATE TABLE IF NOT EXISTS public.barang_masuk
(
    barang_id character(50) COLLATE pg_catalog."default",
    id_barang_masuk character(50) COLLATE pg_catalog."default" NOT NULL,
    jumlah_masuk integer,
    supplier_id integer,
    tanggal_masuk date,
    user_id integer,
    CONSTRAINT barang_masuk_pkey PRIMARY KEY (id_barang_masuk)
);

CREATE TABLE IF NOT EXISTS public.jenis
(
    id_jenis integer NOT NULL,
    nama_jenis character(50) COLLATE pg_catalog."default",
    CONSTRAINT jenis_pkey PRIMARY KEY (id_jenis)
);

CREATE TABLE IF NOT EXISTS public.satuan
(
    id_satuan integer NOT NULL,
    nama_satuan character(50) COLLATE pg_catalog."default",
    CONSTRAINT satuan_pkey PRIMARY KEY (id_satuan)
);

CREATE TABLE IF NOT EXISTS public.supplier
(
    alamat text COLLATE pg_catalog."default",
    id_supplier integer NOT NULL,
    nama_supplier character(50) COLLATE pg_catalog."default",
    no_telp character(20) COLLATE pg_catalog."default",
    CONSTRAINT supplier_pkey PRIMARY KEY (id_supplier)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    created_at integer,
    email character(50) COLLATE pg_catalog."default",
    foto text COLLATE pg_catalog."default",
    id_user integer NOT NULL,
    is_active integer,
    nama character(50) COLLATE pg_catalog."default",
    no_telp character(50) COLLATE pg_catalog."default",
    password character(50) COLLATE pg_catalog."default",
    role character(50) COLLATE pg_catalog."default",
    username character(50) COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id_user)
);
END;